import {generateKeyPairSync,createHash} from "node:crypto";
import {writeFileSync,readFileSync} from "node:fs";
import {signPackage,canonical} from "../container/package.ts";
import {encodePocketPackage,encodeIdentity,decodePocketPackage} from "../examples/hello/.pjm/pocketjs/contracts/spec/pocket-package.ts";
const keys=generateKeyPairSync("ed25519"), key=keys.publicKey.export({format:"der",type:"spki"}).subarray(-32).toString("base64");
const target=process.env.PJM_PACKAGE_TARGET==="android"?"pjm-android":"pjm-ios";
const metadata={appId:"dev.pjm.fixture",version:"1.0.0",minHostAbi:7,entry:"main.pocket" as const,pages:["/"],permissions:["media"],domains:["example.com"],targets:[target]};
const hashPlan=(plan:any)=>({...plan,planHash:"sha256:"+createHash("sha256").update(canonical(plan)).digest("hex")});
const payload=Buffer.from(encodePocketPackage({manifest:Buffer.from("{}"),variants:[{target,hostAbi:7,sections:[{kind:1,bytes:encodeIdentity({output:"fixture",id:metadata.appId,title:"Fixture"})},{kind:2,bytes:Buffer.from(JSON.stringify(hashPlan({app:{id:metadata.appId,version:metadata.version},target:{id:target,hostAbi:7},viewport:{logical:[64,64],physical:[64,64],rasterDensity:1,presentation:"native",policy:"fixed"},features:{"input.touch":true,"text.glyphs.baked":true},companions:[],modality:{form:"takeover",screens:[{role:"primary",logical:[64,64],orientation:"portrait",touch:true,resizable:false}],touch:"primary",pointer:"none",buttons:false,analog:0}}))) },{kind:3,bytes:Buffer.from((process.env.PJM_PACKAGE_VISUAL?"globalThis.__visual=true;ui.setProp(1,64,0xff0000ff);":"")+"let launches=0,frames=0;globalThis.__miniLifecycle=e=>{if(e==='launch')launches++;if(e==='unload'){ui.svcSend('cleanup');ui.svcSend(JSON.stringify({v:1,id:99,kind:'storage.set.v1',args:{key:'cleanup-proof',value:'saved'}}))}};globalThis.frame=(buttons,analog,contacts)=>{if(globalThis.__visual && contacts.length)ui.setProp(1,64,0xffff0000);const incoming=ui.svcPoll();if(incoming)for(const line of incoming.trim().split('\\n')){if(line==='pump')ui.svcSend(JSON.stringify({v:1,id:456,kind:'storage.get.v1',args:{key:'live-proof'}}));else ui.svcSend('reply:'+line)};ui.svcSend('verified:'+launches+':'+(++frames))}\0")},{kind:4,bytes:new Uint8Array()}]}]}));
const valid={payload:payload.toString("base64"),manifest:signPackage(payload,metadata,keys.privateKey),key,valid:true};
const basePlan=JSON.parse(Buffer.from(decodePocketPackage(payload).variants[0].sections.find(section=>section.kind===2)!.bytes).toString());
const rejectedPlans=[{...basePlan,planHash:"bad"},{...basePlan,planHash:"sha256:"+"0".repeat(64)},{...basePlan,modality:{...basePlan.modality,screens:[]}},{...basePlan,modality:{...basePlan.modality,pointer:"mouse"}},{...basePlan,modality:{...basePlan.modality,buttons:true}},{...basePlan,modality:{...basePlan.modality,analog:true}},{...basePlan,modality:{...basePlan.modality,screens:[{...basePlan.modality.screens[0],logical:[32,64]}]}},{...basePlan,features:{"net.http":true}},{...basePlan,features:{"input.touch":1}},{...basePlan,companions:[{id:"other"}]},{...basePlan,viewport:{...basePlan.viewport,presentation:"stretch"}},{app:{id:metadata.appId,version:"2.0.0"},target:{id:target,hostAbi:7},viewport:{logical:[64,64],physical:[64,64],rasterDensity:1}},{app:{id:metadata.appId,version:metadata.version},target:{id:target,hostAbi:7},viewport:{logical:[64,64],physical:[128,64],rasterDensity:1}},{app:{id:metadata.appId,version:metadata.version},target:{id:target,hostAbi:7},viewport:{logical:[64,64],physical:[64,64],rasterDensity:true}}].map(plan=>{if(plan.planHash!=="bad" && plan.planHash!=="sha256:"+"0".repeat(64)){const {planHash,...content}=plan;plan=hashPlan(content);}const decoded=decodePocketPackage(payload);decoded.variants[0].sections.find(section=>section.kind===2)!.bytes=Buffer.from(JSON.stringify(plan));const bytes=Buffer.from(encodePocketPackage(decoded));return {...valid,payload:bytes.toString("base64"),manifest:signPackage(bytes,metadata,keys.privateKey),valid:false};});
const realCases=[];
if(process.env.PJM_PACKAGE_REAL){const bytes=readFileSync(process.env.PJM_PACKAGE_REAL);const decoded=decodePocketPackage(bytes),variant=decoded.variants.find(v=>v.target===target)!;const plan=JSON.parse(Buffer.from(variant.sections.find(s=>s.kind===2)!.bytes).toString());realCases.push({payload:bytes.toString("base64"),manifest:signPackage(bytes,{...metadata,appId:plan.app.id,version:plan.app.version},keys.privateKey),key,valid:true});}
const updateDecoded=decodePocketPackage(payload);
// Hash only plan content; the old hash must not be included.
const updatePlan={...basePlan,app:{...basePlan.app,version:"2.0.0"}};delete updatePlan.planHash;
updateDecoded.variants[0].sections.find(section=>section.kind===2)!.bytes=Buffer.from(JSON.stringify(hashPlan(updatePlan)));
const updatePayload=Buffer.from(encodePocketPackage(updateDecoded));
const update={payload:updatePayload.toString("base64"),manifest:signPackage(updatePayload,{...metadata,version:"2.0.0"},keys.privateKey)};
const peers=[1,2,3].map(index=>{
 const appId=metadata.appId+".peer"+index,decoded=decodePocketPackage(payload),plan={...basePlan,app:{...basePlan.app,id:appId}};delete plan.planHash;
 decoded.variants[0].sections.find(section=>section.kind===1)!.bytes=encodeIdentity({output:"fixture",id:appId,title:"Fixture"});
 decoded.variants[0].sections.find(section=>section.kind===2)!.bytes=Buffer.from(JSON.stringify(hashPlan(plan)));
 const bytes=Buffer.from(encodePocketPackage(decoded));return {payload:bytes.toString("base64"),manifest:signPackage(bytes,{...metadata,appId},keys.privateKey)};
});
writeFileSync(process.argv[2],JSON.stringify([...realCases,{...valid,update,peers},...rejectedPlans,{...valid,manifest:signPackage(payload,{...metadata,appId:"dev.other.app"},keys.privateKey),valid:false},{...valid,payload:Buffer.from("tampered").toString("base64"),valid:false},{...valid,payload:Buffer.from("not a pocket package").toString("base64"),manifest:signPackage(Buffer.from("not a pocket package"),metadata,keys.privateKey),valid:false}]));
