import {test,expect} from 'bun:test';
import {createHash} from 'node:crypto';
import {ReplaySession} from '../devtools/session.ts';
import type {ReplayEngine} from '../devtools/replay.ts';
const payload=Buffer.from('session package'),packageSha256=createHash('sha256').update(payload).digest('hex');
const tape=Buffer.from(JSON.stringify({format:1,packageSha256,launchData:'{}',target:'pjm-ios',window:{width:1,height:1,density:1},steps:[{kind:'completion',record:'{"v":1,"id":1,"ok":true,"data":null}'},{kind:'frame',contacts:[],hits:[],cancelled:[]},{kind:'lifecycle',event:'hide'},{kind:'frame',contacts:[],hits:[],cancelled:[]}]}));
function engines(failFrame=0){const histories:string[][]=[];let closes=0;return {histories,get closes(){return closes;},factory(){const history:string[]=[];histories.push(history);let frame=0;const engine:ReplayEngine={boot(){history.push('boot');},completion(){history.push('completion');},lifecycle(value){history.push(value);},frame(){history.push('frame');frame++;if(frame===failFrame)throw Error('frame failed');return {pixels:new Uint8Array([0,0,0,frame]),effects:['effect '+frame]};},close(){history.push('close');closes++;}};return engine;}};}
test('replay session pauses, steps, ticks and exposes immutable progress',()=>{const provider=engines(),session=new ReplaySession(payload,tape,provider.factory);expect(session.snapshot()).toEqual({state:'paused',step:0,totalSteps:4,frame:0,totalFrames:2,current:null,error:null});expect(Object.isFrozen(session.snapshot())).toBe(true);expect(session.step().step).toBe(1);session.play();expect(session.tick().frame).toBe(1);expect(session.pause().state).toBe('paused');expect(()=>session.tick()).not.toThrow();expect(session.snapshot().step).toBe(2);session.play();while(session.snapshot().state==='playing')session.tick();expect(session.snapshot().state).toBe('completed');expect(provider.histories[0]).toEqual(['boot','completion','frame','hide','frame']);expect(session.close().state).toBe('closed');expect(provider.closes).toBe(1);});
test('seek rebuilds deterministically in either direction and validates bounds',()=>{const provider=engines(),session=new ReplaySession(payload,tape,provider.factory);session.seek(3);expect(session.snapshot()).toMatchObject({state:'paused',step:3,frame:1});const hash=session.snapshot().current;session.seek(1);expect(session.snapshot()).toMatchObject({step:1,frame:0,current:null});session.seek(2);expect(session.snapshot().current).toEqual(hash);expect(provider.histories).toEqual([['boot','close'],['boot','completion','frame','hide','close'],['boot','completion','close'],['boot','completion','frame']]);for(const value of [-1,5,1.5,Infinity])expect(()=>session.seek(value)).toThrow('outside tape');session.close();});
test('engine failure closes once and makes the session recoverable by seek',()=>{const provider=engines(1),session=new ReplaySession(payload,tape,provider.factory);session.step();expect(()=>session.step()).toThrow('frame failed');expect(session.snapshot()).toMatchObject({state:'failed',step:1,frame:0,error:'frame failed'});expect(provider.closes).toBe(1);expect(()=>session.play()).toThrow();expect(()=>session.seek(0)).not.toThrow();expect(session.snapshot().state).toBe('paused');session.close();expect(provider.closes).toBe(2);});
