name: pjm_host
description: Minimal Flutter surface for the PocketJS native engine.
publish_to: none
version: 0.2.0+1
environment:
  sdk: '>=3.11.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.2.0
  hooks: ^2.0.2
  code_assets: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
